# Generated by Django 5.0.4 on 2024-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="eng",
            field=models.CharField(
                default=123, max_length=20, verbose_name="Категория"
            ),
            preserve_default=False,
        ),
    ]
