# Generated by Django 5.0.4 on 2024-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findata", "0002_category_eng"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="rus",
            field=models.CharField(
                default=123, max_length=20, verbose_name="Категория RUS"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="eng",
            field=models.CharField(max_length=20, verbose_name="Категория ENG"),
        ),
    ]
