# Generated by Django 5.0.4 on 2024-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findata", "0003_remove_category_category_category_rus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinDataGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=20, verbose_name="Категория RUS"),
                ),
                ("value", models.FloatField(max_length=10, verbose_name="Сумма")),
                ("operation", models.CharField(max_length=10, verbose_name="Операция")),
                ("date_me", models.CharField(max_length=20, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Финдата сгрупп",
                "verbose_name_plural": "Финдата сгрупп",
            },
        ),
    ]
